# Setup
title:               IFT6758 Project Blog Post
tagline:             'Equipe A08'
description:         'Data science project on NHL data'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
authors:
  kolia:
    name: Kolia Leboucq
    email: kolia.leboucq@umontreal.ca
    github: KoliaLeboucq
  mathieu:
    name: Mathieu Pelo
    email: mathieu.peloquin.1@umontreal.ca
    github: mathieupelo
  marie-eve:
    name: Marie-Eve Picard
    email: marie-eve.picard.2@umontreal.ca
    github: me-pic
  mouaad:
    name: Mouaad El Jemli
    email: mouaad.el.jemli@umontreal.ca
    github: mouaadelj

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
